name: Webpack Build
on:
  push:
    branches:
      - master
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: 63eb967d7ac3b25e184b0a3c3b8e5054582a231c
        BRANCH: dev
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
